# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606ab638db3099abf164a10e58d8f8327b39df0628a2ab6eb4a5eb1aa19557a80da5deeb2699858f5a70c26db205df1e666fd431a12af4739ce0d32877651aa9

test:
  secret_key_base: 291d3e4e4903a0dada57b62fca456ebf58a2dda1050dc820b140664615efc2a9970f2a68f0c1e2dc33f4e442b6c87b4add22af14dbc0d8fded4441b426b24418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
